export const BRAND = {
  name: "ARCHETIVE INFRATECH",
  tagline: "DECORATE YOUR KINGDOM WITH A TOUCH OF ROYALTY",
  designer: "Shubham Jain",
  phones: ["9719131008", "7055770555", "8439696814"],
  email: "Archetypeinfratech@gmail.com",
  instagram: "@archetypeinfratech",
  address:
    "60-Rajendra Nagar, Old Idgah Colony, Near Bal Bharti School, Idgah Bus Stand Road, Agra-282001",
  bank: {
    accountName: "SHUBHAM JAIN",
    accountNo: "00780100025951",
    branch: "AGRA MAIN",
    ifsc: "BARB0AGRAXX (5th character is zero)",
    bankName: "BANK OF BARODA",
    branchAddress: "13 M.G Road Agra U.P Agra",
    msme: "UDYAM-UP-01-0126154",
  },
  website: "archetypeinfratech.com",
  terms: [
    "Payment: Payment is due as per the agreed payment schedule. Delayed payments may attract interest as applicable.",
    "Scope of Work: This invoice covers only the services and materials specifically mentioned herein. Any additional work shall be charged separately.",
    "Taxes: GST and other applicable taxes, if any, shall be charged extra as per Government regulations.",
    "Design & Intellectual Property: All drawings, designs, 3D renders, BOQs, specifications, and related documents remain the exclusive property of ARCHETIVE INFRATECH until full payment is received.",
    "Variations: Any modifications or revisions requested after approval may result in additional charges and extension of project timelines.",
    "Cancellation: Payments made towards design, consultancy, mobilization, procurement, and completed work are non-refundable.",
    "Jurisdiction: Any dispute arising out of this invoice shall be subject to the exclusive jurisdiction of the courts at Agra, Uttar Pradesh.",
    "Acceptance: Payment against this invoice constitutes acceptance of all the above Terms & Conditions.",
    "All services provided by ARCHETIVE INFRATECH are subject to the above Terms & Conditions. Payment of this invoice signifies the client's acceptance of these terms.",
  ],
} as const;
